<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipiosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios = [
            ['id_municipio' => 1, 'id_estado' => 1, 'municipio' => 'ALTO ORINOCO'],
            ['id_municipio' => 2, 'id_estado' => 1, 'municipio' => 'ATABAPO'],
            ['id_municipio' => 3, 'id_estado' => 1, 'municipio' => 'ATURES'],
            ['id_municipio' => 4, 'id_estado' => 1, 'municipio' => 'AUTANA'],
            ['id_municipio' => 5, 'id_estado' => 1, 'municipio' => 'MANAPIARE'],
            ['id_municipio' => 6, 'id_estado' => 1, 'municipio' => 'MAROA'],
            ['id_municipio' => 7, 'id_estado' => 1, 'municipio' => 'RÍO NEGRO'],
            ['id_municipio' => 8, 'id_estado' => 2, 'municipio' => 'ANACO'],
            ['id_municipio' => 9, 'id_estado' => 2, 'municipio' => 'ARAGUA'],
            ['id_municipio' => 10, 'id_estado' => 2, 'municipio' => 'MANUEL EZEQUIEL BRUZUAL'],
            ['id_municipio' => 11, 'id_estado' => 2, 'municipio' => 'DIEGO BAUTISTA URBANEJA'],
            ['id_municipio' => 12, 'id_estado' => 2, 'municipio' => 'FERNANDO PEÑALVER'],
            ['id_municipio' => 13, 'id_estado' => 2, 'municipio' => 'FRANCISCO DEL CARMEN CARVAJAL'],
            ['id_municipio' => 14, 'id_estado' => 2, 'municipio' => 'GENERAL SIR ARTHUR MCGREGOR'],
            ['id_municipio' => 15, 'id_estado' => 2, 'municipio' => 'GUANTA'],
            ['id_municipio' => 16, 'id_estado' => 2, 'municipio' => 'INDENPENDENCIA'],
            ['id_municipio' => 17, 'id_estado' => 2, 'municipio' => 'JOSÉ GREGORIO MONAGAS'],
            ['id_municipio' => 18, 'id_estado' => 2, 'municipio' => 'JUAN ANTONIO SOTILLO'],
            ['id_municipio' => 19, 'id_estado' => 2, 'municipio' => 'JUAN MANUEL CAJIGAL'],
            ['id_municipio' => 20, 'id_estado' => 2, 'municipio' => 'LIBERTAD'],
            ['id_municipio' => 21, 'id_estado' => 2, 'municipio' => 'FRANCISCO DE MIRANDA'],
            ['id_municipio' => 22, 'id_estado' => 2, 'municipio' => 'PEDRO MARÍA FREITES'],
            ['id_municipio' => 23, 'id_estado' => 2, 'municipio' => 'PÍRITU'],
            ['id_municipio' => 24, 'id_estado' => 2, 'municipio' => 'SAN JOSÉ DE GUANIPA'],
            ['id_municipio' => 25, 'id_estado' => 2, 'municipio' => 'SAN JUAN DE CAPISTRANO'],
            ['id_municipio' => 26, 'id_estado' => 2, 'municipio' => 'SANTA ANA'],
            ['id_municipio' => 27, 'id_estado' => 2, 'municipio' => 'SIMÓN BOLÍVAR'],
            ['id_municipio' => 28, 'id_estado' => 2, 'municipio' => 'SIMÓN RODRÍGUEZ'],
            ['id_municipio' => 29, 'id_estado' => 3, 'municipio' => 'ACHAGUAS'],
            ['id_municipio' => 30, 'id_estado' => 3, 'municipio' => 'BIRUACA'],
            ['id_municipio' => 31, 'id_estado' => 3, 'municipio' => 'MUÑÓZ'],
            ['id_municipio' => 32, 'id_estado' => 3, 'municipio' => 'PÁEZ'],
            ['id_municipio' => 33, 'id_estado' => 3, 'municipio' => 'PEDRO CAMEJO'],
            ['id_municipio' => 34, 'id_estado' => 3, 'municipio' => 'RÓMULO GALLEGOS'],
            ['id_municipio' => 35, 'id_estado' => 3, 'municipio' => 'SAN FERNANDO'],
            ['id_municipio' => 36, 'id_estado' => 4, 'municipio' => 'ATANASIO GIRARDOT'],
            ['id_municipio' => 37, 'id_estado' => 4, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 38, 'id_estado' => 4, 'municipio' => 'CAMATAGUA'],
            ['id_municipio' => 39, 'id_estado' => 4, 'municipio' => 'FRANCISCO LINARES ALCÁNTARA'],
            ['id_municipio' => 40, 'id_estado' => 4, 'municipio' => 'JOSÉ ÁNGEL LAMAS'],
            ['id_municipio' => 41, 'id_estado' => 4, 'municipio' => 'JOSÉ FÉLIX RIBAS'],
            ['id_municipio' => 42, 'id_estado' => 4, 'municipio' => 'JOSÉ RAFAEL REVENGA'],
            ['id_municipio' => 43, 'id_estado' => 4, 'municipio' => 'LIBERTADOR'],
            ['id_municipio' => 44, 'id_estado' => 4, 'municipio' => 'MARIO BRICEÑO IRAGORRY'],
            ['id_municipio' => 45, 'id_estado' => 4, 'municipio' => 'OCUMARE DE LA COSTA DE ORO'],
            ['id_municipio' => 46, 'id_estado' => 4, 'municipio' => 'SAN CASIMIRO'],
            ['id_municipio' => 47, 'id_estado' => 4, 'municipio' => 'SAN SEBASTIÁN'],
            ['id_municipio' => 48, 'id_estado' => 4, 'municipio' => 'SANTIAGO MARIÑO'],
            ['id_municipio' => 49, 'id_estado' => 4, 'municipio' => 'SANTOS MICHELENA'],
            ['id_municipio' => 50, 'id_estado' => 4, 'municipio' => 'SUCRE'],
            ['id_municipio' => 51, 'id_estado' => 4, 'municipio' => 'TOVAR'],
            ['id_municipio' => 52, 'id_estado' => 4, 'municipio' => 'URDANETA'],
            ['id_municipio' => 53, 'id_estado' => 4, 'municipio' => 'ZAMORA'],
            ['id_municipio' => 54, 'id_estado' => 5, 'municipio' => 'ALBERTO ARVELO TORREALBA'],
            ['id_municipio' => 55, 'id_estado' => 5, 'municipio' => 'ANDRÉS ELOY BLANCO'],
            ['id_municipio' => 56, 'id_estado' => 5, 'municipio' => 'ANTONIO JOSÉ DE SUCRE'],
            ['id_municipio' => 57, 'id_estado' => 5, 'municipio' => 'ARISMENDI'],
            ['id_municipio' => 58, 'id_estado' => 5, 'municipio' => 'BARINAS'],
            ['id_municipio' => 59, 'id_estado' => 5, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 60, 'id_estado' => 5, 'municipio' => 'CRUZ PAREDES'],
            ['id_municipio' => 61, 'id_estado' => 5, 'municipio' => 'EZEQUIEL ZAMORA'],
            ['id_municipio' => 62, 'id_estado' => 5, 'municipio' => 'OBISPOS'],
            ['id_municipio' => 63, 'id_estado' => 5, 'municipio' => 'PEDRAZA'],
            ['id_municipio' => 64, 'id_estado' => 5, 'municipio' => 'ROJAS'],
            ['id_municipio' => 65, 'id_estado' => 5, 'municipio' => 'SOSA'],
            ['id_municipio' => 66, 'id_estado' => 6, 'municipio' => 'CARONÍ'],
            ['id_municipio' => 67, 'id_estado' => 6, 'municipio' => 'CEDEÑO'],
            ['id_municipio' => 68, 'id_estado' => 6, 'municipio' => 'EL CALLAO'],
            ['id_municipio' => 69, 'id_estado' => 6, 'municipio' => 'GRAN SABANA'],
            ['id_municipio' => 70, 'id_estado' => 6, 'municipio' => 'HERES'],
            ['id_municipio' => 71, 'id_estado' => 6, 'municipio' => 'PIAR'],
            ['id_municipio' => 72, 'id_estado' => 6, 'municipio' => 'ANGOSTURA (RAÚL LEONI)'],
            ['id_municipio' => 73, 'id_estado' => 6, 'municipio' => 'ROSCIO'],
            ['id_municipio' => 74, 'id_estado' => 6, 'municipio' => 'SIFONTES'],
            ['id_municipio' => 75, 'id_estado' => 6, 'municipio' => 'SUCRE'],
            ['id_municipio' => 76, 'id_estado' => 6, 'municipio' => 'PADRE PEDRO CHIEN'],
            ['id_municipio' => 77, 'id_estado' => 7, 'municipio' => 'BEJUMA'],
            ['id_municipio' => 78, 'id_estado' => 7, 'municipio' => 'CARLOS ARVELO'],
            ['id_municipio' => 79, 'id_estado' => 7, 'municipio' => 'DIEGO IBARRA'],
            ['id_municipio' => 80, 'id_estado' => 7, 'municipio' => 'GUACARA'],
            ['id_municipio' => 81, 'id_estado' => 7, 'municipio' => 'JUAN JOSÉ MORA'],
            ['id_municipio' => 82, 'id_estado' => 7, 'municipio' => 'LIBERTADOR'],
            ['id_municipio' => 83, 'id_estado' => 7, 'municipio' => 'LOS GUAYOS'],
            ['id_municipio' => 84, 'id_estado' => 7, 'municipio' => 'MIRANDA'],
            ['id_municipio' => 85, 'id_estado' => 7, 'municipio' => 'MONTALBÁN'],
            ['id_municipio' => 86, 'id_estado' => 7, 'municipio' => 'NAGUANAGUA'],
            ['id_municipio' => 87, 'id_estado' => 7, 'municipio' => 'PUERTO CABELLO'],
            ['id_municipio' => 88, 'id_estado' => 7, 'municipio' => 'SAN DIEGO'],
            ['id_municipio' => 89, 'id_estado' => 7, 'municipio' => 'SAN JOAQUÍN'],
            ['id_municipio' => 90, 'id_estado' => 7, 'municipio' => 'VALENCIA'],
            ['id_municipio' => 91, 'id_estado' => 8, 'municipio' => 'ANZOÁTEGUI'],
            ['id_municipio' => 92, 'id_estado' => 8, 'municipio' => 'TINAQUILLO'],
            ['id_municipio' => 93, 'id_estado' => 8, 'municipio' => 'GIRARDOT'],
            ['id_municipio' => 94, 'id_estado' => 8, 'municipio' => 'LIMA BLANCO'],
            ['id_municipio' => 95, 'id_estado' => 8, 'municipio' => 'PAO DE SAN JUAN BAUTISTA'],
            ['id_municipio' => 96, 'id_estado' => 8, 'municipio' => 'RICAURTE'],
            ['id_municipio' => 97, 'id_estado' => 8, 'municipio' => 'RÓMULO GALLEGOS'],
            ['id_municipio' => 98, 'id_estado' => 8, 'municipio' => 'SAN CARLOS'],
            ['id_municipio' => 99, 'id_estado' => 8, 'municipio' => 'TINACO'],
            ['id_municipio' => 100, 'id_estado' => 9, 'municipio' => 'ANTONIO DÍAZ'],
            ['id_municipio' => 101, 'id_estado' => 9, 'municipio' => 'CASACOIMA'],
            ['id_municipio' => 102, 'id_estado' => 9, 'municipio' => 'PEDERNALES'],
            ['id_municipio' => 103, 'id_estado' => 9, 'municipio' => 'TUCUPITA'],
            ['id_municipio' => 104, 'id_estado' => 10, 'municipio' => 'ACOSTA'],
            ['id_municipio' => 105, 'id_estado' => 10, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 106, 'id_estado' => 10, 'municipio' => 'BUCHIVACOA'],
            ['id_municipio' => 107, 'id_estado' => 10, 'municipio' => 'CACIQUE MANAURE'],
            ['id_municipio' => 108, 'id_estado' => 10, 'municipio' => 'CARIRUBANA'],
            ['id_municipio' => 109, 'id_estado' => 10, 'municipio' => 'COLINA'],
            ['id_municipio' => 110, 'id_estado' => 10, 'municipio' => 'DABAJURO'],
            ['id_municipio' => 111, 'id_estado' => 10, 'municipio' => 'DEMOCRACIA'],
            ['id_municipio' => 112, 'id_estado' => 10, 'municipio' => 'FALCÓN'],
            ['id_municipio' => 113, 'id_estado' => 10, 'municipio' => 'FEDERACIÓN'],
            ['id_municipio' => 114, 'id_estado' => 10, 'municipio' => 'JACURA'],
            ['id_municipio' => 115, 'id_estado' => 10, 'municipio' => 'JOSÉ LAURENCIO SILVA'],
            ['id_municipio' => 116, 'id_estado' => 10, 'municipio' => 'LOS TAQUES'],
            ['id_municipio' => 117, 'id_estado' => 10, 'municipio' => 'MAUROA'],
            ['id_municipio' => 118, 'id_estado' => 10, 'municipio' => 'MIRANDA'],
            ['id_municipio' => 119, 'id_estado' => 10, 'municipio' => 'MONSEÑOR ITURRIZA'],
            ['id_municipio' => 120, 'id_estado' => 10, 'municipio' => 'PALMASOLA'],
            ['id_municipio' => 121, 'id_estado' => 10, 'municipio' => 'PETIT'],
            ['id_municipio' => 122, 'id_estado' => 10, 'municipio' => 'PÍRITU'],
            ['id_municipio' => 123, 'id_estado' => 10, 'municipio' => 'SAN FRANCISCO'],
            ['id_municipio' => 124, 'id_estado' => 10, 'municipio' => 'SUCRE'],
            ['id_municipio' => 125, 'id_estado' => 10, 'municipio' => 'TOCÓPERO'],
            ['id_municipio' => 126, 'id_estado' => 10, 'municipio' => 'UNIÓN'],
            ['id_municipio' => 127, 'id_estado' => 10, 'municipio' => 'URUMACO'],
            ['id_municipio' => 128, 'id_estado' => 10, 'municipio' => 'ZaAMORA'],
            ['id_municipio' => 129, 'id_estado' => 11, 'municipio' => 'CAMAGUÁN'],
            ['id_municipio' => 130, 'id_estado' => 11, 'municipio' => 'CHAGUARAMAS'],
            ['id_municipio' => 131, 'id_estado' => 11, 'municipio' => 'EL SOCORRO'],
            ['id_municipio' => 132, 'id_estado' => 11, 'municipio' => 'JOSÉ FÉLIX RIBAS'],
            ['id_municipio' => 133, 'id_estado' => 11, 'municipio' => 'JOSÉ TADEO MONAGAS'],
            ['id_municipio' => 134, 'id_estado' => 11, 'municipio' => 'JUAN GERMÁN ROSCIO'],
            ['id_municipio' => 135, 'id_estado' => 11, 'municipio' => 'JULIÁN MELLADO'],
            ['id_municipio' => 136, 'id_estado' => 11, 'municipio' => 'LAS MERCEDES'],
            ['id_municipio' => 137, 'id_estado' => 11, 'municipio' => 'LEONARDO INFANTE'],
            ['id_municipio' => 138, 'id_estado' => 11, 'municipio' => 'PEDRO ZARAZA'],
            ['id_municipio' => 139, 'id_estado' => 11, 'municipio' => 'ORTÍZ'],
            ['id_municipio' => 140, 'id_estado' => 11, 'municipio' => 'SAN GERÓNIMO DE GUAYABAL'],
            ['id_municipio' => 141, 'id_estado' => 11, 'municipio' => 'SAN JOSÉ DE GUARIBE'],
            ['id_municipio' => 142, 'id_estado' => 11, 'municipio' => 'SANNTA MARÍA DE IPIRE'],
            ['id_municipio' => 143, 'id_estado' => 11, 'municipio' => 'SEBASTIÁN FRANCISCO DE MIRANDA'],
            ['id_municipio' => 144, 'id_estado' => 12, 'municipio' => 'ANDRÉS ELOY BLANCO'],
            ['id_municipio' => 145, 'id_estado' => 12, 'municipio' => 'CRESPO'],
            ['id_municipio' => 146, 'id_estado' => 12, 'municipio' => 'IRIBARREN'],
            ['id_municipio' => 147, 'id_estado' => 12, 'municipio' => 'JIMÉNEZ'],
            ['id_municipio' => 148, 'id_estado' => 12, 'municipio' => 'MORÁN'],
            ['id_municipio' => 149, 'id_estado' => 12, 'municipio' => 'PALAVECINO'],
            ['id_municipio' => 150, 'id_estado' => 12, 'municipio' => 'SIMÓN PLANAS'],
            ['id_municipio' => 151, 'id_estado' => 12, 'municipio' => 'TORRES'],
            ['id_municipio' => 152, 'id_estado' => 12, 'municipio' => 'URDANETA'],
            ['id_municipio' => 179, 'id_estado' => 13, 'municipio' => 'ALBERTO ADRIANI'],
            ['id_municipio' => 180, 'id_estado' => 13, 'municipio' => 'ANDRÉS BELLO'],
            ['id_municipio' => 181, 'id_estado' => 13, 'municipio' => 'ANTONIO PINTO SALINAS'],
            ['id_municipio' => 182, 'id_estado' => 13, 'municipio' => 'ARICAGUA'],
            ['id_municipio' => 183, 'id_estado' => 13, 'municipio' => 'ARZOBISPO CHACÓN'],
            ['id_municipio' => 184, 'id_estado' => 13, 'municipio' => 'CAMPO ELÍAS'],
            ['id_municipio' => 185, 'id_estado' => 13, 'municipio' => 'CARACCIOLO PARRA OLMEDO'],
            ['id_municipio' => 186, 'id_estado' => 13, 'municipio' => 'CARDENAL QUINTERO'],
            ['id_municipio' => 187, 'id_estado' => 13, 'municipio' => 'GUARAQUE'],
            ['id_municipio' => 188, 'id_estado' => 13, 'municipio' => 'JULIO CÉSAR SALAS'],
            ['id_municipio' => 189, 'id_estado' => 13, 'municipio' => 'JUSTO BRICEÑO'],
            ['id_municipio' => 190, 'id_estado' => 13, 'municipio' => 'LIBERTADOR'],
            ['id_municipio' => 191, 'id_estado' => 13, 'municipio' => 'MIRANDA'],
            ['id_municipio' => 192, 'id_estado' => 13, 'municipio' => 'OBISPO RAMOS DE LORA'],
            ['id_municipio' => 193, 'id_estado' => 13, 'municipio' => 'PADRE NOGUERA'],
            ['id_municipio' => 194, 'id_estado' => 13, 'municipio' => 'PUEBLO LLANO'],
            ['id_municipio' => 195, 'id_estado' => 13, 'municipio' => 'RANGEL'],
            ['id_municipio' => 196, 'id_estado' => 13, 'municipio' => 'RIVAS DÁVILA'],
            ['id_municipio' => 197, 'id_estado' => 13, 'municipio' => 'SANTOS MARQUINA'],
            ['id_municipio' => 198, 'id_estado' => 13, 'municipio' => 'SUCRE'],
            ['id_municipio' => 199, 'id_estado' => 13, 'municipio' => 'TOVAR'],
            ['id_municipio' => 200, 'id_estado' => 13, 'municipio' => 'TULIO FEBRES CORDERO'],
            ['id_municipio' => 201, 'id_estado' => 13, 'municipio' => 'ZEA'],
            ['id_municipio' => 223, 'id_estado' => 14, 'municipio' => 'ACEVEDO'],
            ['id_municipio' => 224, 'id_estado' => 14, 'municipio' => 'ANDRÉS BELLO'],
            ['id_municipio' => 225, 'id_estado' => 14, 'municipio' => 'BARUTA'],
            ['id_municipio' => 226, 'id_estado' => 14, 'municipio' => 'BRIÓN'],
            ['id_municipio' => 227, 'id_estado' => 14, 'municipio' => 'BUROZ'],
            ['id_municipio' => 228, 'id_estado' => 14, 'municipio' => 'CARRIZAL'],
            ['id_municipio' => 229, 'id_estado' => 14, 'municipio' => 'CHACAO'],
            ['id_municipio' => 230, 'id_estado' => 14, 'municipio' => 'CRISTÓBAL ROJAS'],
            ['id_municipio' => 231, 'id_estado' => 14, 'municipio' => 'EL HATILLO'],
            ['id_municipio' => 232, 'id_estado' => 14, 'municipio' => 'GUAICAIPURO'],
            ['id_municipio' => 233, 'id_estado' => 14, 'municipio' => 'INDEPENDENCIA'],
            ['id_municipio' => 234, 'id_estado' => 14, 'municipio' => 'LANDER'],
            ['id_municipio' => 235, 'id_estado' => 14, 'municipio' => 'LOS SALIAS'],
            ['id_municipio' => 236, 'id_estado' => 14, 'municipio' => 'PÁEZ'],
            ['id_municipio' => 237, 'id_estado' => 14, 'municipio' => 'PAZ CASTILLO'],
            ['id_municipio' => 238, 'id_estado' => 14, 'municipio' => 'PEDRO GUAL'],
            ['id_municipio' => 239, 'id_estado' => 14, 'municipio' => 'PLAZA'],
            ['id_municipio' => 240, 'id_estado' => 14, 'municipio' => 'SIMÓN BOLÍVAR'],
            ['id_municipio' => 241, 'id_estado' => 14, 'municipio' => 'SUCRE'],
            ['id_municipio' => 242, 'id_estado' => 14, 'municipio' => 'URDANETA'],
            ['id_municipio' => 243, 'id_estado' => 14, 'municipio' => 'ZAMORA'],
            ['id_municipio' => 258, 'id_estado' => 15, 'municipio' => 'ACOSTA'],
            ['id_municipio' => 259, 'id_estado' => 15, 'municipio' => 'AGUASAY'],
            ['id_municipio' => 260, 'id_estado' => 15, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 261, 'id_estado' => 15, 'municipio' => 'CARIPE'],
            ['id_municipio' => 262, 'id_estado' => 15, 'municipio' => 'CEDEÑO'],
            ['id_municipio' => 263, 'id_estado' => 15, 'municipio' => 'EZEQUIEL ZAMORA'],
            ['id_municipio' => 264, 'id_estado' => 15, 'municipio' => 'LIBERTADOR'],
            ['id_municipio' => 265, 'id_estado' => 15, 'municipio' => 'MATURÍN'],
            ['id_municipio' => 266, 'id_estado' => 15, 'municipio' => 'PIAR'],
            ['id_municipio' => 267, 'id_estado' => 15, 'municipio' => 'PUNCERES'],
            ['id_municipio' => 268, 'id_estado' => 15, 'municipio' => 'SANTA BÁRBARA'],
            ['id_municipio' => 269, 'id_estado' => 15, 'municipio' => 'SOTILLO'],
            ['id_municipio' => 270, 'id_estado' => 15, 'municipio' => 'URACOA'],
            ['id_municipio' => 271, 'id_estado' => 16, 'municipio' => 'ANTOLÍN DEL CAMPO'],
            ['id_municipio' => 272, 'id_estado' => 16, 'municipio' => 'ARISMENDI'],
            ['id_municipio' => 273, 'id_estado' => 16, 'municipio' => 'GARCÍA'],
            ['id_municipio' => 274, 'id_estado' => 16, 'municipio' => 'GÓMEZ'],
            ['id_municipio' => 275, 'id_estado' => 16, 'municipio' => 'MANEIRO'],
            ['id_municipio' => 276, 'id_estado' => 16, 'municipio' => 'MARCANO'],
            ['id_municipio' => 277, 'id_estado' => 16, 'municipio' => 'MARIÑO'],
            ['id_municipio' => 278, 'id_estado' => 16, 'municipio' => 'PENÍNSULA DE MACANAO'],
            ['id_municipio' => 279, 'id_estado' => 16, 'municipio' => 'TUBORES'],
            ['id_municipio' => 280, 'id_estado' => 16, 'municipio' => 'VILLALBA'],
            ['id_municipio' => 281, 'id_estado' => 16, 'municipio' => 'DÍAZ'],
            ['id_municipio' => 282, 'id_estado' => 17, 'municipio' => 'AGUA BLANCA'],
            ['id_municipio' => 283, 'id_estado' => 17, 'municipio' => 'ARAURE'],
            ['id_municipio' => 284, 'id_estado' => 17, 'municipio' => 'ESTELLER'],
            ['id_municipio' => 285, 'id_estado' => 17, 'municipio' => 'GUANARE'],
            ['id_municipio' => 286, 'id_estado' => 17, 'municipio' => 'GUANARITO'],
            ['id_municipio' => 287, 'id_estado' => 17, 'municipio' => 'MONSEÑOR JOSÉ VICENTE DE UNDA'],
            ['id_municipio' => 288, 'id_estado' => 17, 'municipio' => 'OSPINO'],
            ['id_municipio' => 289, 'id_estado' => 17, 'municipio' => 'PÁEZ'],
            ['id_municipio' => 290, 'id_estado' => 17, 'municipio' => 'PAPELÓN'],
            ['id_municipio' => 291, 'id_estado' => 17, 'municipio' => 'SAN GENARO DE BOCONOÍTO'],
            ['id_municipio' => 292, 'id_estado' => 17, 'municipio' => 'SAN RAFAEL DE ONOTO'],
            ['id_municipio' => 293, 'id_estado' => 17, 'municipio' => 'SANTA ROSALÍA'],
            ['id_municipio' => 294, 'id_estado' => 17, 'municipio' => 'SUCRE'],
            ['id_municipio' => 295, 'id_estado' => 17, 'municipio' => 'TURÉN'],
            ['id_municipio' => 296, 'id_estado' => 18, 'municipio' => 'ANDRÉS ELOY BLANCO'],
            ['id_municipio' => 297, 'id_estado' => 18, 'municipio' => 'ANDRÉS MATA'],
            ['id_municipio' => 298, 'id_estado' => 18, 'municipio' => 'ARISMENDI'],
            ['id_municipio' => 299, 'id_estado' => 18, 'municipio' => 'BENÍTEZ'],
            ['id_municipio' => 300, 'id_estado' => 18, 'municipio' => 'BERMÚDEZ'],
            ['id_municipio' => 301, 'id_estado' => 18, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 302, 'id_estado' => 18, 'municipio' => 'CAJIGAL'],
            ['id_municipio' => 303, 'id_estado' => 18, 'municipio' => 'CRUZ SALMERÓN ACOSTA'],
            ['id_municipio' => 304, 'id_estado' => 18, 'municipio' => 'LIBERTADOR'],
            ['id_municipio' => 305, 'id_estado' => 18, 'municipio' => 'MARIÑO'],
            ['id_municipio' => 306, 'id_estado' => 18, 'municipio' => 'MEJÍA'],
            ['id_municipio' => 307, 'id_estado' => 18, 'municipio' => 'MONTES'],
            ['id_municipio' => 308, 'id_estado' => 18, 'municipio' => 'RIBERO'],
            ['id_municipio' => 309, 'id_estado' => 18, 'municipio' => 'SUCRE'],
            ['id_municipio' => 310, 'id_estado' => 18, 'municipio' => 'VALDÉZ'],
            ['id_municipio' => 341, 'id_estado' => 19, 'municipio' => 'ANDRÉS BELLO'],
            ['id_municipio' => 342, 'id_estado' => 19, 'municipio' => 'ANTONIO RÓMULO COSTA'],
            ['id_municipio' => 343, 'id_estado' => 19, 'municipio' => 'AYACUCHO'],
            ['id_municipio' => 344, 'id_estado' => 19, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 345, 'id_estado' => 19, 'municipio' => 'CÁRDENAS'],
            ['id_municipio' => 346, 'id_estado' => 19, 'municipio' => 'CÓRDOBA'],
            ['id_municipio' => 347, 'id_estado' => 19, 'municipio' => 'FERNÁNDEZ FEO'],
            ['id_municipio' => 348, 'id_estado' => 19, 'municipio' => 'FRANCISCO DE MIRANDA'],
            ['id_municipio' => 349, 'id_estado' => 19, 'municipio' => 'GARCÍA DE HEVIA'],
            ['id_municipio' => 350, 'id_estado' => 19, 'municipio' => 'GUÁSIMOS'],
            ['id_municipio' => 351, 'id_estado' => 19, 'municipio' => 'INDEPENDENCIA'],
            ['id_municipio' => 352, 'id_estado' => 19, 'municipio' => 'JÁUREGUI'],
            ['id_municipio' => 353, 'id_estado' => 19, 'municipio' => 'JOSÉ MARÍA VARGAS'],
            ['id_municipio' => 354, 'id_estado' => 19, 'municipio' => 'JUNÍN'],
            ['id_municipio' => 355, 'id_estado' => 19, 'municipio' => 'LIBERTAD'],
            ['id_municipio' => 356, 'id_estado' => 19, 'municipio' => 'LIBERTADOR'],
            ['id_municipio' => 357, 'id_estado' => 19, 'municipio' => 'LOBATERA'],
            ['id_municipio' => 358, 'id_estado' => 19, 'municipio' => 'MICHELENA'],
            ['id_municipio' => 359, 'id_estado' => 19, 'municipio' => 'PANAMERICANO'],
            ['id_municipio' => 360, 'id_estado' => 19, 'municipio' => 'PEDRO MARÍA UREÑA'],
            ['id_municipio' => 361, 'id_estado' => 19, 'municipio' => 'RAFAEL URDANETA'],
            ['id_municipio' => 362, 'id_estado' => 19, 'municipio' => 'SAMUEL DARÍO MALDONADO'],
            ['id_municipio' => 363, 'id_estado' => 19, 'municipio' => 'SAN CRISTÓBAL'],
            ['id_municipio' => 364, 'id_estado' => 19, 'municipio' => 'SEBORUCO'],
            ['id_municipio' => 365, 'id_estado' => 19, 'municipio' => 'SIMÓN RODRÍGUEZ'],
            ['id_municipio' => 366, 'id_estado' => 19, 'municipio' => 'SUCRE'],
            ['id_municipio' => 367, 'id_estado' => 19, 'municipio' => 'TORBES'],
            ['id_municipio' => 368, 'id_estado' => 19, 'municipio' => 'URIBANTE'],
            ['id_municipio' => 369, 'id_estado' => 19, 'municipio' => 'SAN JUDAS TADEO'],
            ['id_municipio' => 370, 'id_estado' => 20, 'municipio' => 'ANDRÉS BELLO'],
            ['id_municipio' => 371, 'id_estado' => 20, 'municipio' => 'BOCONÓ'],
            ['id_municipio' => 372, 'id_estado' => 20, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 373, 'id_estado' => 20, 'municipio' => 'CANDELARIA'],
            ['id_municipio' => 374, 'id_estado' => 20, 'municipio' => 'CARACHE'],
            ['id_municipio' => 375, 'id_estado' => 20, 'municipio' => 'ESCUQUE'],
            ['id_municipio' => 376, 'id_estado' => 20, 'municipio' => 'JOSÉ FELIPE MÁRQUEZ CAÑIZALES'],
            ['id_municipio' => 377, 'id_estado' => 20, 'municipio' => 'JUAN VICENTE CAMPOS ELÍAS'],
            ['id_municipio' => 378, 'id_estado' => 20, 'municipio' => 'LA CEIBA'],
            ['id_municipio' => 379, 'id_estado' => 20, 'municipio' => 'MIRANDA'],
            ['id_municipio' => 381, 'id_estado' => 20, 'municipio' => 'MOTATÁN'],
            ['id_municipio' => 382, 'id_estado' => 20, 'municipio' => 'PAMPÁN'],
            ['id_municipio' => 383, 'id_estado' => 20, 'municipio' => 'PAMPANITO'],
            ['id_municipio' => 384, 'id_estado' => 20, 'municipio' => 'RAFAEL RANGEL'],
            ['id_municipio' => 385, 'id_estado' => 20, 'municipio' => 'SAN RAFAEL DE CARVAJAL'],
            ['id_municipio' => 386, 'id_estado' => 20, 'municipio' => 'SUCRE'],
            ['id_municipio' => 387, 'id_estado' => 20, 'municipio' => 'TRUJILLO'],
            ['id_municipio' => 388, 'id_estado' => 20, 'municipio' => 'URDANETA'],
            ['id_municipio' => 389, 'id_estado' => 20, 'municipio' => 'VALERA'],
            ['id_municipio' => 390, 'id_estado' => 21, 'municipio' => 'VARGAS'],
            ['id_municipio' => 391, 'id_estado' => 22, 'municipio' => 'ARÍSTIDES BASTIDAS'],
            ['id_municipio' => 392, 'id_estado' => 22, 'municipio' => 'BOLÍVAR'],
            ['id_municipio' => 407, 'id_estado' => 22, 'municipio' => 'BRUZUAL'],
            ['id_municipio' => 408, 'id_estado' => 22, 'municipio' => 'COCOROTE'],
            ['id_municipio' => 409, 'id_estado' => 22, 'municipio' => 'INDEPENDENCIA'],
            ['id_municipio' => 410, 'id_estado' => 22, 'municipio' => 'JOSÉ ANTONIO PÁEZ'],
            ['id_municipio' => 411, 'id_estado' => 22, 'municipio' => 'LA TRINIDAD'],
            ['id_municipio' => 412, 'id_estado' => 22, 'municipio' => 'MANUEL MONGE'],
            ['id_municipio' => 413, 'id_estado' => 22, 'municipio' => 'NIRGUA'],
            ['id_municipio' => 414, 'id_estado' => 22, 'municipio' => 'PEÑA'],
            ['id_municipio' => 415, 'id_estado' => 22, 'municipio' => 'SAN FELIPE'],
            ['id_municipio' => 416, 'id_estado' => 22, 'municipio' => 'SUCRE'],
            ['id_municipio' => 417, 'id_estado' => 22, 'municipio' => 'URACHICHE'],
            ['id_municipio' => 418, 'id_estado' => 22, 'municipio' => 'JOSÉ JOAQUÍN VEROES'],
            ['id_municipio' => 441, 'id_estado' => 23, 'municipio' => 'ALMIRANTE PADILLA'],
            ['id_municipio' => 442, 'id_estado' => 23, 'municipio' => 'BARALT'],
            ['id_municipio' => 443, 'id_estado' => 23, 'municipio' => 'CABIMAS'],
            ['id_municipio' => 444, 'id_estado' => 23, 'municipio' => 'CATATUMBO'],
            ['id_municipio' => 445, 'id_estado' => 23, 'municipio' => 'COLÓN'],
            ['id_municipio' => 446, 'id_estado' => 23, 'municipio' => 'FRANCISCO JAVIER PULGAR'],
            ['id_municipio' => 447, 'id_estado' => 23, 'municipio' => 'PÁEZ'],
            ['id_municipio' => 448, 'id_estado' => 23, 'municipio' => 'JESÚS ENRIQUE LOSADA'],
            ['id_municipio' => 449, 'id_estado' => 23, 'municipio' => 'JESÚS MARÍA SEMPRÚN'],
            ['id_municipio' => 450, 'id_estado' => 23, 'municipio' => 'LA CAÑADA DE URDANETA'],
            ['id_municipio' => 451, 'id_estado' => 23, 'municipio' => 'LAGUNILLAS'],
            ['id_municipio' => 452, 'id_estado' => 23, 'municipio' => 'MACHIQUES DE PERIJÁ'],
            ['id_municipio' => 453, 'id_estado' => 23, 'municipio' => 'MARA'],
            ['id_municipio' => 454, 'id_estado' => 23, 'municipio' => 'MARACAIBO'],
            ['id_municipio' => 455, 'id_estado' => 23, 'municipio' => 'MIRANDA'],
            ['id_municipio' => 456, 'id_estado' => 23, 'municipio' => 'ROSARIO DE PERIJÁ'],
            ['id_municipio' => 457, 'id_estado' => 23, 'municipio' => 'SAN FRANCISCO'],
            ['id_municipio' => 458, 'id_estado' => 23, 'municipio' => 'SANTA RITA'],
            ['id_municipio' => 459, 'id_estado' => 23, 'municipio' => 'SIMÓN BOLÍVAR'],
            ['id_municipio' => 460, 'id_estado' => 23, 'municipio' => 'SUCRE'],
            ['id_municipio' => 461, 'id_estado' => 23, 'municipio' => 'VALMORE RODRÍGUEZ'],
            ['id_municipio' => 462, 'id_estado' => 24, 'municipio' => 'LIBERTADOR'],
        ];

        DB::table('municipios')->insert($municipios);
    }
}
